const USER_APPLY_STATUS = {
    DEFAULT: "DEFAULT",
    PENDING: "PENDING",
    PAYMENT: "PAYMENT",
    BOOKED: "BOOKED",
};

const MENTOR_APPLY_STATUS = {
    DEFAULT: "DEFAULT",
    PENDING: "PENDING",
    WAIT_PAYMENT: "WAIT_PAYMENT",
    BOOKED: "BOOKED",
};

export { USER_APPLY_STATUS, MENTOR_APPLY_STATUS };
